# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

scenario:
  simpl: ['']
  ll: ['copt']
  clusters: [37, 128, 256, 512, 1024]
  opts: [Co2L-3H]

enable:
  retrieve_data: true