# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

enable:
  retrieve_data: true

renewable_techs: ["wind", "solar"]