# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-usa
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pip
  - mamba # esp for windows build


  - pypsa==0.23.0
  - atlite>=0.2.5

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - numpy
  - geopandas
  - powerplantmatching
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely>=2
  - progressbar2
  - pyomo
  - matplotlib

  # Keep in conda environment when calling ipython
  - ipython
  - jupyter
  - notebook
  - ipykernel

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - country_converter
  - tabula-py

  - fs<=2.4.14

  - pip:
    - vresutils==0.3.1
    - tsam>=1.1.0
    # - git+https://github.com/pypsa/pypsa.git
    - gurobipy
