__default__:
    account: iazevedo
    partition: serc
    time: 00:30:00 # time limit for each job
    nodes: 1
    ntasks-per-node: 8 #Request n cores be allocated per node.
    chdir: $GROUP_HOME/kamran/pypsa-usa/workflow
    output: log/slurm/{rule}-%j.out
    error: log/slurm/err_{rule}-%j.err
