# Copyright 2021-2022 Martha Frysztacki (KIT)

scenarios:
  # all:
  #   interconnect: usa
  #   clusters: 200
  #   opts:
  #     [
  #       Co2L0.0,
  #       Co2L0.1,
  #       Co2L0.2,
  #       Co2L0.3,
  #       Co2L0.4,
  #       Co2L0.5,
  #       Co2L0.6,
  #       Co2L0.7,
  #       Co2L0.8,
  #       Co2L0.9,
  #       Co2L1.0,
  #     ]
  #   ll: [vopt, v1.0, v1.1, v1.2]
  all:
    interconnect: usa
    clusters: 10
    opts:
      [
        Co2L0.0,
        Co2L1.0,
      ]
    ll: [vopt, v1.0]

  test:
    interconnect: texas
    clusters: 5
    opts:
      [
        Co2L0.0,
        Co2L0.5,
        Co2L1.0,
      ]
    ll: v1.0

subworkflow: "pypsa-eur/"

zenodo_repository:
  url: "https://zenodo.org/record/4538590/files/USATestSystem.zip"
  use: true # if false, network is created from powersimdata, if true, network is created from zenodo_repo. Currently 'false' does not function

countries: [US]

allowed_carriers:
  [wind, solar, offwind, hydro, coal, nuclear, ng, oil, geothermal]
committable_carriers: []
extendable_carriers: [solar, wind, offwind]

electricity:
  voltages: [230., 345., 500., 765.]
  voltage_simplified: 230
  co2limit: 1.4728e+9 # 0.8 * 1.841e+9
  co2base: 1.841e+9 #base_from_2020 Locations of the 1,841 MMmt of CO2 emissions from the current state of the grid in 2020.

  extendable_carriers:
    Generator: []
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: [H2 pipeline]

renewable:
  wind:
    potential: simple # or conservative
  solar:
    potential: simple # or conservative
  hydro:
    potential: simple

solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: true
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
