__default__:
    account: iazevedo
    partition: serc
    time: 00:30:00 # time limit for each job
    chdir: $GROUP_HOME/kamran/pypsa-usa/workflow
    output: logs/slurm/{rule}-%j.out
    error: logs/slurm/err_{rule}-%j.err
