name: pypsa-usa
channels:
  - conda-forge
  - bioconda

dependencies:
  - python>=3.8
  - pip

  - pypsa
  - atlite

  # Dependencies of the workflow itself
  - pandas>=0.24.0,<2.1
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - numpy
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely>=2
  - progressbar2
  - pyomo
  - matplotlib

  # Keep in conda environment when calling ipython
  - ipython
  - jupyter
  - notebook
  - ipykernel

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio

  # TODO: check these dependencies
  - geopy
  - tqdm
  - pytz
  - country_converter
  - tabula-py

  - fs<=2.4.14

  - pip:
    - vresutils==0.3.1
    - tsam>=1.1.0
    - gurobipy
